#!/bin/bash
CC=g++

LIBS="-larmadillo -lhdf5 -lhdf5_hl -lhdf5_cpp -lhdf5_hl_cpp -lfftw3 -lfftw3_omp -lvisa -lsfml-window
-lsfml-graphics -llapack -lgslcblas -lgsl -ljsoncpp -lpaxpro"

noExt=$(echo $1 | cut -f 1 -d '.')

# Compile application
${CC} -std=c++11 -fopenmp -c -o "${noExt}.o" $1
${CC} -std=c++11 -fopenmp -o "${noExt}.out" "${noExt}.o" "${@:2}" ${LIBS}
